### ISSUE TITLE
Data Source: datasets

### ISSUE THREAD

**Issue by fitzoh** [kvrhdn/terraform-provider-honeycombio#15]
A data source that retrieves a list of all datasets present in the account.
This would be useful for creating standardized boards/triggers across all datasets.

Could potentially include the ability to filter based on the name (ie all datasets that end with `-prod`).

Requires Honeycomb API support.

**Comment by kvrhdn** [comment]
For reference: I'd imagine this could work very similar to [`aws_availability_zones`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/availability_zones#filter-configuration-block).
