### ISSUE TITLE
Able to set invalid "COUNT" columns

### ISSUE THREAD

**Issue by fitzoh** [kvrhdn/terraform-provider-honeycombio#18]
While trying to work around #17 I tried setting a column with my `COUNT` column.

The terraform apply succeeded but upon trying to view it I received the following error:
![Capture](https://user-images.githubusercontent.com/131809/90091999-c8ab7700-dcf5-11ea-954e-4ce9ab0b92fc.PNG)

This validation may belong at the API layer (where it is missing), but might be worth considering at the terraform layer as well

**Comment by kvrhdn** [comment]
Yeah, it would be good to validate that `column` is not set when `op = COUNT`.

I'll also report this to Honeycomb support later today. Ideally, their API handler would refuse this immediately.

**Comment by kvrhdn** [comment]
I should be able to fix together with #17 later today 🙂

**Comment by kvrhdn** [comment]
I can confirm the triggers API allows you to specify a column with COUNT:

<img width="1205" alt="Screenshot 2020-08-13 at 19 01 07" src="https://user-images.githubusercontent.com/7748404/90164376-9d796400-dd97-11ea-8eae-9664c2afba52.png">

Request log:

```
2020/08/13 19:00:46 Sending request

POST /1/triggers/kvrhdn-terraform-provider-honeycombio HTTP/1.1
Host: api.honeycomb.io
User-Agent: Terraform/0.13.0 (+https://www.terraform.io) Terraform-Plugin-SDK/2.0.1 terraform-provider-honeycombio/dev
Content-Length: 313
Content-Type: application/json
X-Honeycomb-Team: ***
Accept-Encoding: gzip

{"name":"Test calculation op COUNT with a column","query":{"calculations":[{"op":"COUNT","column":"duration_ms"}],"filter_combination":"AND"},"frequency":900,"threshold":{"op":"\u003e","value":100},"recipients":[{"type":"email","target":"hello@example.com"},{"type":"marker","target":"Trigger - slow requests"}]}

2020/08/13 19:00:46 Received response

HTTP/1.1 201 Created
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Type: application/json
Date: Thu, 13 Aug 2020 17:00:46 GMT
Last-Modified: Thu, 13 Aug 2020 17:00:46 GMT
Location: /1/triggers/kvrhdn/terraform-provider-honeycombio/qjka31sHhmh
Vary: Accept-Encoding

{"name":"Test calculation op COUNT with a column","frequency":900,"disabled":false,"query":{"calculations":[{"column":"duration_ms","op":"COUNT"}],"time_range":900},"threshold":{"op":">","value":100},"recipients":[{"type":"email","target":"hello@example.com","id":"ADFR34ZJJg3"},{"type":"marker","target":"Trigger - slow requests","id":"2gunZszQQ4j"}],"id":"qjka31sHhmh"}
```

But when I want to do something similar with the boards API, I get a proper error 🤔 

```
2020/08/13 19:06:57 Sending request

POST /1/boards HTTP/1.1
Host: api.honeycomb.io
User-Agent: Terraform/0.13.0 (+https://www.terraform.io) Terraform-Plugin-SDK/2.0.1 terraform-provider-honeycombio/dev
Content-Length: 222
Content-Type: application/json
X-Honeycomb-Team: ***
Accept-Encoding: gzip

{"name":"Test calculation op COUNT with a column","style":"list","queries":[{"dataset":"kvrhdn/terraform-provider-honeycombio","query":{"calculations":[{"op":"COUNT","column":"duration_ms"}],"filter_combination":"AND"}}]}

2020/08/13 19:06:58 Received response

HTTP/1.1 422 Unprocessable Entity
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Type: application/json
Date: Thu, 13 Aug 2020 17:06:58 GMT
Vary: Accept-Encoding

{"error":"COUNT operator does not take a column"}
```

But I can't reproduce the error you have @fitzoh.

**Comment by fitzoh** [comment]
Should have clarified: If you view/edit the trigger it automatically removes the removes the column and displays the count correctly.

If you click on the query itself from the `All triggers` page it brings you to the query editor page where it fails to execute due to the column.
