### ISSUE TITLE
Support `limit` on queries

### ISSUE THREAD

**Issue by fitzoh** [kvrhdn/terraform-provider-honeycombio#20]
https://docs.honeycomb.io/api/query-specification/#fields-on-a-query-specification

**Comment by kvrhdn** [comment]
Sure, this would be a great addition!

TODO (from the top of my head):

- implement https://github.com/kvrhdn/go-honeycombio/issues/6
- add `limit` field to [the `honeycombio_query` schema](https://github.com/kvrhdn/terraform-provider-honeycombio/blob/main/honeycombio/data_source_query.go#L55)
- I believe triggers support [a limited query spec](https://docs.honeycomb.io/api/triggers/#fields-on-a-trigger) so we should validate that `limit` is not set, [similar to this](https://github.com/kvrhdn/terraform-provider-honeycombio/blob/main/honeycombio/resource_trigger.go#L41)

**Comment by kvrhdn** [comment]
Support for limits has been added with go-honeycombio [0.0.11](https://github.com/kvrhdn/go-honeycombio/releases/tag/v0.0.11).
