### ISSUE TITLE
Support Import operations

### ISSUE THREAD

**Issue by fitzoh** [kvrhdn/terraform-provider-honeycombio#36]
I was attempting to import a manually created board into terraform, but that does not appear to be documented.

From looking at the docs, no resources currently support importing.

**Comment by kvrhdn** [comment]
Yeah, that's right. It's something you have to explicitly enable/implement per resource.
Which resource would you like to import?

Since reading `honeycombio_board` only requires an ID this can be implemented with [`schema.ImportStatePassthrough`](https://www.terraform.io/docs/extend/resources/import.html#importer-state-function).

Importing triggers is a bit more difficult since we need both the ID and the datasaet to retrieve the trigger.

**Comment by kvrhdn** [comment]
Okay, I've quickly added `schema.ImportStatePassthrough` and I can confirm importing boards works fine 👍🏻  I'll clean that up tomorrow and release it.

Importing triggers should also be possible, it will just a bit more implementation work because we need both the dataset and the ID.

**Comment by fitzoh** [comment]
>Which resource would you like to import?

Primarily interested in boards at the moment (that's the issue I ran into), was torn between opening per resource issues or a blanket one. I could see someone wanting to import a trigger, not really seeing a marker import use case.

>Okay, I've quickly added schema.ImportStatePassthrough and I can confirm importing boards works fine 👍🏻 I'll clean that up tomorrow and release it.

Awesome, thanks

>Importing triggers should also be possible, it will just a bit more implementation work because we need both the dataset and the ID.

Something like `terraform import honeycombio_trigger.whatever <dataset>/<id>`?

**Comment by kvrhdn** [comment]
> Primarily interested in boards at the moment (that's the issue I ran into), was torn between opening per resource issues or a blanket one. I could see someone wanting to import a trigger, not really seeing a marker import use case.

Agree. One issue for all imports is fine imo, we can add both implementations simultaneously.

> Something like `terraform import honeycombio_trigger.whatever <dataset>/<id>`?

Yeah, but we have to keep in mind that `/` is a valid character in a dataset name. I have a dataset named  `kvrhdn/terraform-provider-honeycombio` for example.

But we might be able to write a function that always uses the last `/` in the string. I think we can assume an ID will only contain alphanumeric characters and especially no `/`...

**Comment by fitzoh** [comment]
>Yeah, but we have to keep in mind that / is a valid character in a dataset name. I have a dataset named kvrhdn/terraform-provider-honeycombio for example.

Well that's interesting...
So I created a dataset called `test/dataset`, and the url becomes `<team>/datasets/test-dataset`.

If I try to create `test-dataset`, it appears to just be a noop.


anyways...
>But we might be able to write a function that always uses the last / in the string. I think we can assume an ID will only contain alphanumeric characters and especially no /...

Yeah, that sounds reasonable

**Comment by kvrhdn** [comment]
> Well that's interesting...
> So I created a dataset called test/dataset, and the url becomes <team>/datasets/test-dataset.
> 
> If I try to create test-dataset later, it appears to just be a noop.

Yeah, that's also something I discovered: if you put the dataset in the URL, it has to be sanitized (replace `/` by `-`) but if you use it in the body it should stay the same...

go-honeycombio has a little extra logic for this when calling the markers and triggers API
https://github.com/kvrhdn/go-honeycombio/blob/main/client.go#L185

**Comment by kvrhdn** [comment]
All in all not a lot of work to implement this 😀 

I'll add an importer to `honeycombio_trigger` as well and make a new release tomorrow.

**Comment by fitzoh** [comment]
sweet, thanks again

**Comment by kvrhdn** [comment]
Import has been implemented for boards and triggers! 🙂
