### ISSUE TITLE
Resource: derived column

### ISSUE THREAD

**Issue by kvrhdn** [kvrhdn/terraform-provider-honeycombio#4]
A resource to manage the derived columns of a dataset.

More information: https://docs.honeycomb.io/working-with-your-data/customizing-your-query/derived-columns/
Reference: https://docs.honeycomb.io/working-with-your-data/customizing-your-query/derived-columns/reference/#docs-sidebar
~~API: *there is no API yet for this*~~ This is okay now :)

Possible Terraform schema:

```hcl
resource "honeycombio_derived_column" "example" {
  dataset     = "my-dataset"
  alias       = "duration_ms_log10"
  description = "Log10 of duration_ms"

  function = "LOG10($\"duration_ms\")"
}
```

**Comment by jlsalmon** [comment]
Is there any info on when this API might be available?

**Comment by kvrhdn** [comment]
Not that I'm aware of. I have seen this been requested before on the Pollinators Slack, so they are already tracking it. But I don't know if it is part of the roadmap for the near future.
Your best bet is probably to post something on Slack again.
