### ISSUE TITLE
Graceful handling of 409 Conflict when creating duplicate column

### ISSUE THREAD

**Issue by tyler-boyd** [kvrhdn/terraform-provider-honeycombio#59]
Hey,

Would it be possible to have the provider not treat HTTP 409s as an error? When I try to run terraform apply with an empty state and a dataset with columns already exists, I get this error:  

```
╷
│ Error: 409 Conflict: Can't insert, column already exists with this key_name or alias.
│
│   on columns.tf line 15, in resource "honeycombio_column" "column":
│   15: resource "honeycombio_column" "column" {
│
╵
```

It'd be awesome if in this case it updated the existing column instead of having to manually import all of them.

Thanks!

**Comment by kvrhdn** [comment]
Hi Tyler, thank you for your contributions! This request seems reasonable, I'm actually wondering why it doesn't already work that way... I'll check out your PRs in the next few days, at the latest end of next week.

**Comment by mattjw** [comment]
Hi 👋.  Has there been a regression with this feature? I've hit the same 409 error, when Terraform tries to provision a column that exists already:

```
│ Error: 409 Conflict: Could not add or update the column: column already exists with this key_name or alias.
│
│   with honeycombio_column.myservice_columns["mycolumn"],
│   on honeycomb-dashboards.tf line 68, in resource "honeycombio_column" "myservice_columns":
│   68: resource "honeycombio_column" "myservice_columns" {
```

This is with v0.15.0 (June 2023) of the provider.

**Comment by jharley** [comment]
Hi, @mattjw!

The logic changed in [v0.12.0](https://github.com/honeycombio/terraform-provider-honeycombio/blob/main/CHANGELOG.md#0120-dec-16-2022) of the provider as it started doing column deletes and the behaviour of what amounted to "automatic import" is not a normal -- and arguably a dangerous -- Terraform workflow.

For the same reason, I'm pretty against any sort of `allow_preexisting` or `create_if_missing` options as I don't think they match the general Terraform workflow.

**Comment by mattjw** [comment]
@jharley thanks for the reply. And that makes perfect sense. It did seem a little unusual to me too.

One a related topic, I was wondering if it's possible for the provider to validate the presence of required columns at plan-time? Rather than waiting to get a nasty surprise at apply?

Let me know what you think, and if there's appetite for this I'm happy to raise a feature enhancement request. (Presumably as an issue in this repo?)
