### ISSUE TITLE
expression update in honeycombio_derived_colum enforces resource recreation

### ISSUE THREAD

**Issue by olegy2008** [kvrhdn/terraform-provider-honeycombio#77]
Hey! 
Thanks for this operator!
While updating `expression` value in `honeycombio_derived_column` resource provider forces resource replacement while it's working fine in UI and API supports in-place updates: https://docs.honeycomb.io/api/derived-columns/#update-a-derived-column.
In our case deletion of derived_column is failing because it is referenced in SLOs.
https://github.com/kvrhdn/terraform-provider-honeycombio/blob/7ec7ca02cde626c5be91f5a7b8524afb29b55f3b/honeycombio/resource_derived_column.go#L29-L33

Is this a bug or there are reasons for this behavior (recreation of resource instead of in-place update)?

**Comment by olegy2008** [comment]
Hey @kvrhdn!
Is there any chance to get your opinion about that?

**Comment by kvrhdn** [comment]
I'm guessing documentation used to say it couldn't be updated. That's how I documented it in go-honeycombio as well
https://github.com/kvrhdn/go-honeycombio/blob/596fd485338ddfd4db58b3b456b3f494a8aff4d4/derived_column.go#L51-L55

Agree the provider should simply update expressions in place.

**Comment by kvrhdn** [comment]
Fixed by #78, thanks!
